# utils/emailer.py
# Sends email alerts when threats are detected
# Junior Developer: Sarvani

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# ─────────────────────────────────────────────
# EMAIL CONFIGURATION
# ─────────────────────────────────────────────

SENDER_EMAIL = os.getenv("ALERT_EMAIL")
SENDER_PASSWORD = os.getenv("ALERT_EMAIL_PASSWORD")
RECEIVER_EMAIL = os.getenv("RECEIVER_EMAIL")
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587


# ─────────────────────────────────────────────
# BUILD EMAIL BODY
# ─────────────────────────────────────────────

def build_email_body(threat_data: dict, ai_summary: str = None) -> str:
    """
    Builds a professional HTML email body for a threat alert.

    Args:
        threat_data (dict): Dictionary containing threat details
        ai_summary (str): AI-generated incident summary from Groq

    Returns:
        str: HTML formatted email body
    """
    timestamp = threat_data.get("timestamp", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    attack_type = threat_data.get("attack_type", "Unknown")
    severity = threat_data.get("severity", "Unknown")
    confidence = threat_data.get("confidence", 0)
    source_ip = threat_data.get("source_ip", "Unknown")
    action = threat_data.get("recommended_action", "Under investigation")

    # Set severity color
    severity_colors = {
        "Critical": "#ff0000",
        "High": "#ff6600",
        "Medium": "#ffaa00",
        "Low": "#00aa00"
    }
    color = severity_colors.get(severity, "#888888")

    # Build HTML body
    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; padding: 20px;">

        <h2 style="color: {color};">
            🚨 Cybersecurity Threat Alert — {severity} Severity
        </h2>

        <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%;">
            <tr style="background-color: #f2f2f2;">
                <td><strong>Field</strong></td>
                <td><strong>Details</strong></td>
            </tr>
            <tr>
                <td>Attack Type</td>
                <td><strong>{attack_type}</strong></td>
            </tr>
            <tr>
                <td>Severity Level</td>
                <td style="color: {color};"><strong>{severity}</strong></td>
            </tr>
            <tr>
                <td>Confidence Score</td>
                <td>{confidence:.2%}</td>
            </tr>
            <tr>
                <td>Source IP Address</td>
                <td>{source_ip}</td>
            </tr>
            <tr>
                <td>Detection Time</td>
                <td>{timestamp}</td>
            </tr>
            <tr>
                <td>Recommended Action</td>
                <td><strong>{action}</strong></td>
            </tr>
        </table>

        <br>

        <h3>🤖 AI Incident Summary</h3>
        <p style="background-color: #f9f9f9; padding: 15px; border-left: 4px solid {color};">
            {ai_summary if ai_summary else "AI summary not available."}
        </p>

        <br>
        <p style="color: #888; font-size: 12px;">
            This alert was automatically generated by the
            Enterprise Cybersecurity Threat Detection System.
        </p>

    </body>
    </html>
    """
    return html


# ─────────────────────────────────────────────
# SEND EMAIL ALERT
# ─────────────────────────────────────────────

def send_threat_alert(threat_data: dict, ai_summary: str = None) -> bool:
    """
    Sends an email alert for a detected threat.

    Args:
        threat_data (dict): Dictionary containing threat details
        ai_summary (str): AI-generated incident summary from Groq

    Returns:
        bool: True if email sent successfully, False otherwise
    """

    # Check if email credentials are configured
    if not SENDER_EMAIL or not SENDER_PASSWORD or not RECEIVER_EMAIL:
        print("[WARNING] Email credentials not configured in .env — skipping email alert")
        return False

    try:
        # ── Build the email ──
        msg = MIMEMultipart("alternative")
        msg["Subject"] = (
            f"🚨 [{threat_data.get('severity', 'Unknown')}] "
            f"Threat Detected: {threat_data.get('attack_type', 'Unknown')} "
            f"from {threat_data.get('source_ip', 'Unknown')}"
        )
        msg["From"] = SENDER_EMAIL
        msg["To"] = RECEIVER_EMAIL

        # Attach HTML body
        html_body = build_email_body(threat_data, ai_summary)
        msg.attach(MIMEText(html_body, "html"))

        # ── Send the email ──
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())

        print(f"[EMAIL] Alert sent successfully for {threat_data.get('attack_type')} attack")
        return True

    except Exception as e:
        print(f"[ERROR] Failed to send email alert: {e}")
        return False